.class public final Li/a/a$a;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Li/a/a;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = "a"
.end annotation


# direct methods
.method public static a(Li/a/a;I)[Ljava/lang/Object;
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "<T:",
            "Ljava/lang/Object;",
            ">(",
            "Li/a/a<",
            "TT;>;I)[TT;"
        }
    .end annotation

    const-string p1, "this"

    invoke-static {p0, p1}, Lh/c0/d/m;->f(Ljava/lang/Object;Ljava/lang/String;)V

    .line 1
    new-instance p0, Lh/m;

    const-string p1, "Generated by Android Extensions automatically"

    invoke-direct {p0, p1}, Lh/m;-><init>(Ljava/lang/String;)V

    throw p0
.end method
